cc_savefile/cc_savefile/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from .views import (IndexPage,
    ModalFormSubmitSuccess, InvitationToDownloadGameView,
    FAQPage)
from users.forms import EmailAuthenticationForm

urlpatterns = [
    url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^modal-submit-success/$', ModalFormSubmitSuccess.as_view(), name='modal_submit_success'),
    url(r'^invitation/$', InvitationToDownloadGameView.as_view(), name='invitation_to_download_game'),
    url(r'^faq/$', FAQPage.as_view(), name='faq'),

    url(r'^', include('users.urls')),

    url(r'^', include('gamesaves.urls')),

    url(r'^', include('quiz.urls')),

    url(r'^', include('store.urls')),

    url(r'^select2/', include('django_select2.urls')),

    url(r'^auth/', include('djoser.urls.authtoken')),

    # Custom login form using email as label for username
    url(r'^accounts/login/$', auth_views.login,
        {'authentication_form':EmailAuthenticationForm, 'template_name': 'registration/login.html'}, name='auth_login'),

    # Custom password reset form using html email template
    url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'auth_password_reset_done',
         'email_template_name': 'registration/password_reset_email.txt',
         'html_email_template_name': 'registration/password_reset_email.html'},
        name='auth_password_reset'),

    url(r'^accounts/', include('registration.backends.hmac.urls')),

    # url(r'session_security/', include('session_security.urls')),

    url(r'^nested_admin/', include('nested_admin.urls')),

    # url(r'^admin/django-ses/', include('django_ses.urls')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # Adds the media URL to be used in development
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )


from django.conf.urls import (
handler400, handler403, handler404, handler500
)

handler400 = 'cc_savefile.views.bad_request'
handler403 = 'cc_savefile.views.permission_denied'
handler404 = 'cc_savefile.views.page_not_found'
handler500 = 'cc_savefile.views.server_error'

cc_savefile/quiz/urls.py
# TEMPLATE URLS
from django.conf.urls import include, url
from django.conf.urls import url
from .views import QuizView, QuizCompleteView


urlpatterns = [
    url(r'^quiz/complete/(?P<pk>.*)/$',
        QuizCompleteView.as_view(),
        name="quiz_sitting_complete"),

    url(r'^quiz/(?P<pk>.*)/$',
        QuizView.as_view(),
        name="quiz_sitting"),
]

# API URLS
from rest_framework import routers
from .api.viewsets import QuizViewSet

router = routers.DefaultRouter()

router.register(r'quiz', QuizViewSet)

urlpatterns += [
    url(r'^api/', include(router.urls)),
]

cc_savefile/seo/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel


class PageMetaTags(TimeStampedModel):
    OGTYPES = (
        (1, "article"),
        (2, "website"),
        (3, "book"),
        (4, "profile")
    )
    page_id = models.SlugField(
            "Page ID", unique=True, max_length=200,
            help_text='Page ID (for template use). Autogenerated. No touchy!')

    # Meta Fields
    og_title = models.CharField(
            "og:title", max_length=200, blank=True, null=True,
            help_text="Will also be used for TITLE")
    og_keywords = models.CharField("og:keywords", max_length=200, blank=True,
                                   null=True,
                                   help_text='Comma separated')
    og_image = models.ImageField(
            "og:image", upload_to="og-images", null=True, blank=True,
            help_text='If possible, at least 1200px x 1200px')
    og_description = models.TextField(
            "og:description", null=True, blank=True,
            help_text="Will also be used for META DESCRIPTION")

    og_types = models.PositiveIntegerField("og:type", null=True, blank=True,
                                           choices=OGTYPES, default=1)

    def __unicode__(self):
        return "%s" % self.page_id

    class Meta:
        verbose_name = "Page Meta Tags"
        verbose_name_plural = "Page Meta Tags"
        ordering = ("page_id", )

cc_savefile/seo/views.py
from django.shortcuts import render

# Create your views here.

cc_savefile/seo/templates/seo/meta_tags.html
{% load staticfiles seo_tags %}

{% if meta_tags %}
{% spaceless %}
    {% if meta_tags.og_title %}
        <title>{% metablock %}{{ meta_tags.og_title }}{% endmetablock %}</title>
        <meta property="og:title" itemprop="name" content="{% metablock %}{{ meta_tags.og_title }}{% endmetablock %}">
    {% else %}
        <title>{% metablock %}ChemCaper EDU{% endmetablock %}</title>
        <meta property="og:title" content="{% metablock %}ChemCaper Pilot Program{% endmetablock %}">
    {% endif %}

    {% if meta_tags.og_keywords %}
        <meta property="og:keywords" name="keywords" content="{% metablock %}{{ meta_tags.og_keywords }}{% endmetablock %}">
    {% else %}
        {# Default #}
        <meta name="keywords" content="chemcaper, portal">
    {% endif %}

    {% if meta_tags.og_description %}
        <meta property="og:description" content="{% metablock %}{{ meta_tags.og_description }}{% endmetablock %}">
        <meta name="description" content="{% metablock %}{{ meta_tags.og_description }}{% endmetablock %}">
    {% else %}
        {# Default #}
        <meta property="og:description" content="{% metablock %}Welcome to
              ChemCaper EDU
              {% endmetablock %}">
        <meta name="description" content="{% metablock %}Welcome to
              ChemCaper EDU
              {% endmetablock %}">
    {% endif %}

    {% if meta_tags.og_types %}
        <meta property="og:type" content="{% metablock %}{{ meta_tags.get_og_types_display }}{% endmetablock %}">
    {% endif %}

    {% if meta_tags.og_image %}
        <meta property="og:image" content="{% metablock %}https://{{ request.get_host }}{{ MEDIA_URL }}{% thumbnail meta_tags.og_image.url 1200 1200 %}{% endmetablock %}">
    {% else %}
        <meta property="og:image"
              content="{% metablock %}https://{{ request.get_host }}{% static 'img/carousel-index-2.jpg' %}{% endmetablock %}">
    {% endif %}

    <meta property="og:url" content="{% metablock %}{{ request.build_absolute_uri }}{% endmetablock %}">
{% endspaceless %}

{% comment %}
<meta property="og:image" content="{% metablock %}
{% if object.university.logo %}
    {{ MEDIA_URL }}{% thumbnail object.university.logo.url 1200 1200 %}
{% endif %}
    {% endmetablock %}">


{% endcomment %}
{% endif %}