cc_savefile/cc_savefile/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from .views import (IndexPage,
    ModalFormSubmitSuccess, InvitationToDownloadGameView,
    FAQPage)
from users.forms import EmailAuthenticationForm

urlpatterns = [
    url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^modal-submit-success/$', ModalFormSubmitSuccess.as_view(), name='modal_submit_success'),
    url(r'^invitation/$', InvitationToDownloadGameView.as_view(), name='invitation_to_download_game'),
    url(r'^faq/$', FAQPage.as_view(), name='faq'),

    url(r'^', include('users.urls')),

    url(r'^', include('gamesaves.urls')),

    url(r'^', include('quiz.urls')),

    url(r'^', include('store.urls')),

    url(r'^select2/', include('django_select2.urls')),

    url(r'^auth/', include('djoser.urls.authtoken')),

    # Custom login form using email as label for username
    url(r'^accounts/login/$', auth_views.login,
        {'authentication_form':EmailAuthenticationForm, 'template_name': 'registration/login.html'}, name='auth_login'),

    # Custom password reset form using html email template
    url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'auth_password_reset_done',
         'email_template_name': 'registration/password_reset_email.txt',
         'html_email_template_name': 'registration/password_reset_email.html'},
        name='auth_password_reset'),

    url(r'^accounts/', include('registration.backends.hmac.urls')),

    # url(r'session_security/', include('session_security.urls')),

    url(r'^nested_admin/', include('nested_admin.urls')),

    # url(r'^admin/django-ses/', include('django_ses.urls')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # Adds the media URL to be used in development
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )


from django.conf.urls import (
handler400, handler403, handler404, handler500
)

handler400 = 'cc_savefile.views.bad_request'
handler403 = 'cc_savefile.views.permission_denied'
handler404 = 'cc_savefile.views.page_not_found'
handler500 = 'cc_savefile.views.server_error'

cc_savefile/quiz/urls.py
# TEMPLATE URLS
from django.conf.urls import include, url
from django.conf.urls import url
from .views import QuizView, QuizCompleteView


urlpatterns = [
    url(r'^quiz/complete/(?P<pk>.*)/$',
        QuizCompleteView.as_view(),
        name="quiz_sitting_complete"),

    url(r'^quiz/(?P<pk>.*)/$',
        QuizView.as_view(),
        name="quiz_sitting"),
]

# API URLS
from rest_framework import routers
from .api.viewsets import QuizViewSet

router = routers.DefaultRouter()

router.register(r'quiz', QuizViewSet)

urlpatterns += [
    url(r'^api/', include(router.urls)),
]

cc_savefile/quiz/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import TimeStampedModel
from django.contrib.postgres.fields import JSONField

class Quiz(TimeStampedModel):
    title = models.CharField(_('Title'), max_length=500, blank=True, null=True)
    is_active = models.BooleanField(_('Is Active'), default=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _('Quiz')
        verbose_name_plural = _('Quizzes')


class Question(TimeStampedModel):
    ANSWER = 1
    SINGLE = 2
    MULTI = 3
    DRAW = 4

    TYPE_LIST = (
        (ANSWER, _("Short Answer")),
        (SINGLE, _("Single Choice")),
        (MULTI, _("Multiple Choice")),
        (DRAW, _("Drawing")),
    )

    quiz = models.ForeignKey("quiz.Quiz", verbose_name=_('Quiz'),
                    blank=True, null=True)
    content = models.TextField(_('Question'), blank=True, null=True)
    q_type = models.IntegerField(_("Type of question"), choices=TYPE_LIST,
                default=ANSWER, blank=True, null=True)
    answer_text = models.CharField(_('Answer'), max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to = 'question_images', null=True, blank=True)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    class Meta:
        ordering = ('order', )

    def __unicode__(self):
        return "%s - %s" % (self.content, self.get_q_type_display())



class AnswerChoice(TimeStampedModel):
    question = models.ForeignKey("quiz.Question", verbose_name=_('Question'),
                    blank=True, null=True)
    content = models.CharField(_('Answer'), max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to = 'answer_choice_images', null=True, blank=True)
    is_correct_answer = models.BooleanField(_('Is Correct Answer'), default=False)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    def __unicode__(self):
        return "%s - %s" % (self.question, self.content)

    class Meta:
        ordering = ('order', )


class AnswerAttributeValue(TimeStampedModel):
    answer = models.ForeignKey("quiz.AnswerChoice", verbose_name=_('Answer'),
                    blank=True, null=True)
    quiz_attribute = models.ForeignKey("quiz.QuizAttribute", verbose_name=_('Quiz Attribute'),
                    blank=True, null=True)
    value = models.DecimalField(_('Value'), default=1, decimal_places=2, max_digits=10)
    is_active = models.BooleanField(_('Is Active'), default=True)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    def __unicode__(self):
        return "%s - %s (%s)" % (self.answer, self.quiz_attribute, self.value)

    class Meta:
        ordering = ('order', )


class QuizAttribute(TimeStampedModel):
    title = models.CharField(_('Title'), max_length=500, blank=True, null=True)
    description = models.TextField(_('Description'), max_length=1000, blank=True, null=True)
    is_active = models.BooleanField(_('Is Active'), default=True)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    def __unicode__(self):
        return "%s" % self.title

    class Meta:
        ordering = ('order', )


class Sitting(TimeStampedModel):
    '''
    Model to store quiz sitting of the MasterUser.
    '''
    masteruser = models.ForeignKey("users.MasterUser", blank=True, null=True)
    quiz = models.ForeignKey("quiz.Quiz", verbose_name=_('Quiz'),
                    blank=True, null=True)
    answers = JSONField(_('Answers'), blank=True, null=True)
    trialgamesave = models.ForeignKey("gamesaves.TrialGameSave", verbose_name=_('Trial Game Save Session'),
                    blank=True, null=True)
    is_completed = models.BooleanField(_('Is Completed'), default=False)


    def show_answers (self):
        data = []
        for q_data in self.answers:
            question_order = q_data["order"] + 1
            question_id = q_data["question"]
            answer = q_data["answer"]
            is_correct = q_data["is_correct"]
            question_obj = Question.objects.get(id=question_id)
            if question_obj.q_type == Question.ANSWER:
                obj = {"order": question_order, "question": question_obj, "answer": answer, "is_correct": is_correct}
            elif question_obj.q_type in [Question.SINGLE, Question.MULTI]:
                obj = {"order": question_order, "question": question_obj, "answer": [AnswerChoice.objects.get(id=a) for a in answer], "choices": question_obj.answerchoice_set.all(), "is_correct": is_correct}
            if question_obj.q_type == Question.DRAW:
                sittingimage = SittingImage.objects.get(id=answer)
                obj = {"order": question_order, "question": question_obj, "answer": sittingimage.image, "is_correct": is_correct}
            data.append(obj)
        return data

    def find_answer(self, question):
        data = ""
        for q_data in self.show_answers():
            question_obj = q_data["question"]
            if question == question_obj:
                data = q_data
        return data


class SittingImage(TimeStampedModel):
    '''
    Model to store uploaded images per sitting, linked to a Question.
    '''
    sitting = models.ForeignKey("quiz.Sitting", blank=True, null=True)
    question = models.ForeignKey("quiz.Question", verbose_name=_('Question'),
                    blank=True, null=True)
    image = models.ImageField(upload_to = 'answer_images', null=True, blank=True)

cc_savefile/quiz/templates/quiz/quiz_sitting.html
{% extends 'base.html' %}
{% load i18n staticfiles form_utils %}

{% block title %}{{ quiz.title }}{% endblock %}
{% block header %}{% endblock %}
{% block main %}
<div class="row">
    <div class="col-md-12">
        {% if not complete %}
        <form method="post" id="quiz-sitting-form" class="form-centered form-quiz-sitting alt">
            {% csrf_token %}
            <!-- <h2>{{ quiz.title }}</h2> -->

            <input name="masteruser" type="hidden" value="{{ token_str }}">
            <input name="trialgamesave" type="hidden" value="{% if trialgamesave %}{{ trialgamesave.id }}{% endif %}">
            {% for question in quiz.question_set.all %}
            <fieldset data-page="{{ forloop.counter }}">
                <div class="question_container">
                    <div class="row question_row">
                        <div class="col-xs-4">
                            {% if question.image %}
                            {# <div class='image_container'> #}
                                {# <img src="{{ question.image.url }}" data-toggle="cc_modal" data-target="#quizModal" class="question_image"> #}
                                <img src="{{ question.image.url }}" class="question_image">
                            {# </div> #}
                            {% endif %}
                        </div>

                        <div class="col-xs-8 speech-bubble">
                            <div class="question_header">
                                <!-- {{ forloop.counter }}) --> {{ question.content }}
                            </div>
                        </div>
                    </div>



                    {% comment %}
                    {% if question.id in empty_error %}
                    <br><span>Please answer this question</span>
                    {% endif %}
                    {% endcomment %}


                    {% if question.q_type == 1 %}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="question_text">
                                    <input type="text" name="question_{{ question.order }}_pk_{{ question.id }}">
                                </div>
                            </div>
                        </div>

                    {% elif question.q_type == 2 %}
                        
                        {% for answer in question.answerchoice_set.all %}
                            {% if forloop.counter|divisibleby:4 %}
                                <div class="question_radio_container row">
                            {% endif %}
                                <div class="col-sm-3 col-xs-6">
                                    <div class="question_radio">
                                        <input type="radio" name="question_{{ question.order }}_pk_{{ question.id }}" id="question_{{ question.order }}_pk_{{ question.id }}_answer_{{ answer.id }}" value="{{ answer.id }}">
                                        <label for="question_{{ question.order }}_pk_{{ question.id }}_answer_{{ answer.id }}">
                                            {{ answer.content }}
                                            {% if answer.image %}
                                                <div class='image_container'>
                                                    <img src="{{ answer.image.url }}" class="answer_image">
                                                    {# <img src="{{ answer.image.url }}" data-toggle="cc_modal" data-target="#quizModal" class="answer_image"> #}
                                                </div>
                                            {% endif %}

                                        </label>
                                    </div>
                                </div>
                            {% if forloop.counter|divisibleby:4 %}
                                </div>
                            {% endif %}
                        {% endfor %}


                    {% elif question.q_type == 3 %}
                        {% for answer in question.answerchoice_set.all %}
                            {% if forloop.counter|divisibleby:4 %}
                                <div class="question_checkbox_container row">
                            {% endif %}
                            <div class="col-sm-3 col-xs-6">
                                <div class="question_checkbox">
                                    <input type="checkbox" name="question_{{ question.order }}_pk_{{ question.id }}" id="question_{{ question.order }}_pk_{{ question.id }}_answer_{{ answer.id }}" value="{{ answer.id }}">
                                    <label for="question_{{ question.order }}_pk_{{ question.id }}_answer_{{ answer.id }}">
                                        {{ answer.content }}
                                        {% if answer.image %}
                                            <div class='image_container'>
                                                <img src="{{ answer.image.url }}" class="answer_image">
                                                {# <img src="{{ answer.image.url }}" data-toggle="cc_modal" data-target="#quizModal" class="answer_image"> #}
                                            </div>
                                        {% endif %}

                                    </label>
                                </div>
                            </div>
                            {% if forloop.counter|divisibleby:4 %}
                                </div>
                            {% endif %}
                        {% endfor %}
                        

                    {% elif question.q_type == 4 %}
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="canvasDiv" data-qid="{{ question.id }}"></div>
                                {# <div class="btn btn-primary" id="canvasSubmitBtn">Submit Signature</div> #}
                                <div class="btn btn-default canvasClearBtn" data-qid="{{ question.id }}">Clear Drawing</div>

                                {# Data URL for your signature will go here! #}
                                <textarea class="form-control hide canvasDataUrl" data-qid="{{ question.id }}" rows="10" name="question_{{ question.order }}_pk_{{ question.id }}"></textarea>

                                {# <img id="canvasCompletedImage" src="" alt="Your signature will go here!"/> #}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </fieldset>
            {% endfor %}
            <input type="hidden" name="browsermode" value="{% if browsermode %}1{% else %}0{% endif %}">
          <button class="btn-form-prev btn">PREV</button>
          <button class="btn-form-next btn">NEXT</button>
          <button type="submit" class="btn btn-form-submit" id="quiz-submit"></button>
        </form>
        {% else %}
            <h2 style="text-align:center;">{{ message }}</h2>
            {% if not browsermode %}<center><a href="uniwebview://donequiz" class="btn btn-lg btn-success">Okay</a></center>{% endif %}
        {% endif %}
    </div>
</div>

{% endblock %}


{% block footer %}
<!-- Modal -->
<div class="modal fade" id="quizModal" tabindex="-1" role="dialog" aria-labelledby="quizModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close btn btn-sm btn-default" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="quizModalLabel">Test header</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

cc_savefile/quiz/templates/quiz/quiz_sitting_complete.html
{% extends 'base.html' %}
{% load i18n staticfiles form_utils %}

{% block title %}{% endblock %}

{% comment %}
{% block main %}
<div class="row">
    <div class="col-md-6">
        <div id="quiz-complete">
            <h3 class="quiz-complete-content">Thank you for completing the<br>{{ quiz.title }}</h3>
            <p class="quiz-complete-content">You may now return to the game.</p>
            <center><a href="uniwebview://donequiz" class="btn btn-success">Okay</a></center>
        </div>
    </div>
    <div class="col-md-6"></div>
</div>

{% endblock %}
{% endcomment %}

{% block main %}
<div class="row form-centered">
    <div class="col-md-12">
        <div id="quiz-complete">
            <h3 class="quiz-complete-content">Thank you for completing the<br>{{ quiz.title }}</h3>
            <p class="quiz-complete-content">You may now return to the game.</p>
            {% if not browsermode %}<center><a href="uniwebview://donequiz" class="btn btn-lg btn-success">Okay</a></center>{% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block header %}{% endblock %}
{% block footer %}{% endblock %}