cc_savefile/cc_savefile/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from .views import (IndexPage,
    ModalFormSubmitSuccess, InvitationToDownloadGameView,
    FAQPage)
from users.forms import EmailAuthenticationForm

urlpatterns = [
    url(r'^$', IndexPage.as_view(), name='home'),
    url(r'^modal-submit-success/$', ModalFormSubmitSuccess.as_view(), name='modal_submit_success'),
    url(r'^invitation/$', InvitationToDownloadGameView.as_view(), name='invitation_to_download_game'),
    url(r'^faq/$', FAQPage.as_view(), name='faq'),

    url(r'^', include('users.urls')),

    url(r'^', include('gamesaves.urls')),

    url(r'^', include('quiz.urls')),

    url(r'^', include('store.urls')),

    url(r'^select2/', include('django_select2.urls')),

    url(r'^auth/', include('djoser.urls.authtoken')),

    # Custom login form using email as label for username
    url(r'^accounts/login/$', auth_views.login,
        {'authentication_form':EmailAuthenticationForm, 'template_name': 'registration/login.html'}, name='auth_login'),

    # Custom password reset form using html email template
    url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'auth_password_reset_done',
         'email_template_name': 'registration/password_reset_email.txt',
         'html_email_template_name': 'registration/password_reset_email.html'},
        name='auth_password_reset'),

    url(r'^accounts/', include('registration.backends.hmac.urls')),

    # url(r'session_security/', include('session_security.urls')),

    url(r'^nested_admin/', include('nested_admin.urls')),

    # url(r'^admin/django-ses/', include('django_ses.urls')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    # Adds the media URL to be used in development
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )


from django.conf.urls import (
handler400, handler403, handler404, handler500
)

handler400 = 'cc_savefile.views.bad_request'
handler403 = 'cc_savefile.views.permission_denied'
handler404 = 'cc_savefile.views.page_not_found'
handler500 = 'cc_savefile.views.server_error'

cc_savefile/quiz/urls.py
# TEMPLATE URLS
from django.conf.urls import include, url
from django.conf.urls import url
from .views import QuizView, QuizCompleteView


urlpatterns = [
    url(r'^quiz/complete/(?P<pk>.*)/$',
        QuizCompleteView.as_view(),
        name="quiz_sitting_complete"),

    url(r'^quiz/(?P<pk>.*)/$',
        QuizView.as_view(),
        name="quiz_sitting"),
]

# API URLS
from rest_framework import routers
from .api.viewsets import QuizViewSet

router = routers.DefaultRouter()

router.register(r'quiz', QuizViewSet)

urlpatterns += [
    url(r'^api/', include(router.urls)),
]

cc_savefile/users/urls.py
# TEMPLATE URLS
from django.conf.urls import include, url
from django.conf.urls import url
from .views import (
    RegisterView,
    RegisterThankYouView,
    RequestTrialView,
    SignupLoginView,
    SchoolUserManagementView,
    SchoolUserDetailView,
    SchoolUserUpdateProfileView,

    RedeemLicenseView,
    RedeemLicenseThankYouView,
    ActivateLicenseView,
    InviteLicenseView,
    CancelInvitationView,
    LicenseSetUsernameView,
    LicenseSetUsernameThankYouView,

    RequestMoreFreeFullView,
    RequestMoreDemoView,
    send_invite_license_email,

    UploadCsvView,
    license_import_template_export,
    quiz_sittings_export,
    generate_licenses,
    export_licenses_as_csv,
    gamesession_csv_export,

    trialaccount_send_activation_email,
    trialaccount_activate, trialaccount_deactivate,
    trialaccount_sendinvitation, trialaccount_getprogress,
    TrialAccountReportView,

    fullaccount_send_activation_email,
    fullaccount_deactivate, fullaccount_activate,
    fullaccount_sendinvitation,

    test_send_email
    )
from .utils import resend_activation_email
from .account_views import (PasswordResetBeforeActivationView,
                        ResendActivationEmailView,
                        ResendActivationEmailSuccessView,)
from .ajax import check_redeem_code

urlpatterns = [
    url(r'^test_send_email/$',
        test_send_email,
        name='test_send_email'),

    url(r'^register/$',
        RegisterView.as_view(),
        name='register_form'),

    url(r'^thank-you/$',
        RegisterThankYouView.as_view(),
        name='register_thank_you'),

    url(r'^request-trial/$',
        RequestTrialView.as_view(),
        name='request_trial'),

    url(r'^signup-login/$',
        SignupLoginView.as_view(),
        name='signup_login'),

    url(r'^users/ajax/check-redeem-code/$',
        check_redeem_code,
        name="users_ajax_check_redeem_code"),

    url(r'^users/resend-activation-email/$',
        resend_activation_email,
        name="users_resend_activation_email"),

    url(r'^users/resend-activation-email-form/$',
        ResendActivationEmailView.as_view(),
        name="users_resend_activation_email_form"),

    url(r'^users/resend-activation-email-success/(?P<mode>.*)/$',
        ResendActivationEmailSuccessView.as_view(),
        name="users_resend_activation_email_success"),

    url(r'^users/set-password-before-activate/(?P<activation_key>[-:\w]+)/$',
        PasswordResetBeforeActivationView.as_view(),
        name="set_password_before_activate"),

    url(r'^users/management/$',
        SchoolUserManagementView.as_view(),
        name="schooluser_management"),

    url(r'^users/account/$',
        SchoolUserDetailView.as_view(),
        name="schooluser_detail"),

    url(r'^users/account/update/$',
        SchoolUserUpdateProfileView.as_view(),
        name="schooluser_update"),

    url(r'^users/upload-csv/$',
        UploadCsvView.as_view(),
        name="import_account_from_csv"),

    url(r'^users/send-invite/',
        send_invite_license_email,
        name="send_invite_license_email"),

    url(r'^users/export-license-template/',
        license_import_template_export,
        name="license_import_template_export"),

    url(r'^users/generate-licenses/(?P<account_type>.*)/',
        generate_licenses,
        name="generate_licenses"),

    url(r'^users/export-licenses-as-csv/',
        export_licenses_as_csv,
        name="export_licenses_as_csv"),

    url(r'^users/export-quiz-sittings/',
        quiz_sittings_export,
        name="quiz_sittings_export"),

    url(r'^users/export-gamesession-data/',
        gamesession_csv_export,
        name="gamesession_csv_export"),

    # Redeem
    url(r'^redeem/$',
        RedeemLicenseView.as_view(),
        name="license_redeem"),

    url(r'^redeem/success/$',
        RedeemLicenseThankYouView.as_view(),
        name="license_redeem_thankyou"),

    # License Activation
    url(r'^license/activate/(?P<activation_key>[-:\w]+)/$',
        ActivateLicenseView.as_view(),
        name="activate_license"),

    # url(r'^invite_license/$',
    #     InviteLicenseView.as_view(),
    #     name="invite_license"),

    url(r'^invite_license/(?P<user_id>.*)/$',
        InviteLicenseView.as_view(),
        name="invite_license"),

    url(r'^set-username/success/$',
        LicenseSetUsernameThankYouView.as_view(),
        name="license_set_username_thankyou"),

    url(r'^set-username/(?P<activation_key>[-:\w]+)/$',
        LicenseSetUsernameView.as_view(),
        name="license_set_username"),

    url(r'^cancel-invitation/$',
        CancelInvitationView.as_view(),
        name="cancel_invitation"),

    # Request more licenses
    url(r'^request-free-full/$',
        RequestMoreFreeFullView.as_view(),
        name="request_more_free_full"),

    url(r'^request-demo/$',
        RequestMoreDemoView.as_view(),
        name="request_more_demo"),


    # trial account urls
    url(r'^users/trial-send-activation-email/$',
        trialaccount_send_activation_email,
        name="trialaccount_send_activation_email"),

    url(r'^users/trial-deactivate/$',
        trialaccount_deactivate,
        name="trialaccount_deactivate"),

    url(r'^users/trial-activate/$',
        trialaccount_activate,
        name="trialaccount_activate"),

    url(r'^users/trial-send-invitation-to-download/$',
        trialaccount_sendinvitation,
        name="trialaccount_sendinvitation"),

    url(r'^users/trial-get-progress/$',
        trialaccount_getprogress,
        name="trialaccount_getprogress"),

    url(r'^users/demo-license-report/(?P<user_id>.*)/$',
        TrialAccountReportView.as_view(),
        name="trialaccount_report"),


    url(r'^users/full-send-activation-email/$',
        fullaccount_send_activation_email,
        name="fullaccount_send_activation_email"),

    url(r'^users/full-deactivate/$',
        fullaccount_deactivate,
        name="fullaccount_deactivate"),

    url(r'^users/full-activate/$',
        fullaccount_activate,
        name="fullaccount_activate"),

    url(r'^users/full-send-invitation-to-download/$',
        fullaccount_sendinvitation,
        name="fullaccount_sendinvitation"),
]


# API URLS
from rest_framework import routers
from .api.viewsets import MasterUserViewSet

router = routers.DefaultRouter()

router.register(r'masteruser', MasterUserViewSet)

urlpatterns += [
    url(r'^api/', include(router.urls)),
]

cc_savefile/quiz/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import TimeStampedModel
from django.contrib.postgres.fields import JSONField

class Quiz(TimeStampedModel):
    title = models.CharField(_('Title'), max_length=500, blank=True, null=True)
    is_active = models.BooleanField(_('Is Active'), default=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _('Quiz')
        verbose_name_plural = _('Quizzes')


class Question(TimeStampedModel):
    ANSWER = 1
    SINGLE = 2
    MULTI = 3
    DRAW = 4

    TYPE_LIST = (
        (ANSWER, _("Short Answer")),
        (SINGLE, _("Single Choice")),
        (MULTI, _("Multiple Choice")),
        (DRAW, _("Drawing")),
    )

    quiz = models.ForeignKey("quiz.Quiz", verbose_name=_('Quiz'),
                    blank=True, null=True)
    content = models.TextField(_('Question'), blank=True, null=True)
    q_type = models.IntegerField(_("Type of question"), choices=TYPE_LIST,
                default=ANSWER, blank=True, null=True)
    answer_text = models.CharField(_('Answer'), max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to = 'question_images', null=True, blank=True)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    class Meta:
        ordering = ('order', )

    def __unicode__(self):
        return "%s - %s" % (self.content, self.get_q_type_display())



class AnswerChoice(TimeStampedModel):
    question = models.ForeignKey("quiz.Question", verbose_name=_('Question'),
                    blank=True, null=True)
    content = models.CharField(_('Answer'), max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to = 'answer_choice_images', null=True, blank=True)
    is_correct_answer = models.BooleanField(_('Is Correct Answer'), default=False)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    def __unicode__(self):
        return "%s - %s" % (self.question, self.content)

    class Meta:
        ordering = ('order', )


class AnswerAttributeValue(TimeStampedModel):
    answer = models.ForeignKey("quiz.AnswerChoice", verbose_name=_('Answer'),
                    blank=True, null=True)
    quiz_attribute = models.ForeignKey("quiz.QuizAttribute", verbose_name=_('Quiz Attribute'),
                    blank=True, null=True)
    value = models.DecimalField(_('Value'), default=1, decimal_places=2, max_digits=10)
    is_active = models.BooleanField(_('Is Active'), default=True)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    def __unicode__(self):
        return "%s - %s (%s)" % (self.answer, self.quiz_attribute, self.value)

    class Meta:
        ordering = ('order', )


class QuizAttribute(TimeStampedModel):
    title = models.CharField(_('Title'), max_length=500, blank=True, null=True)
    description = models.TextField(_('Description'), max_length=1000, blank=True, null=True)
    is_active = models.BooleanField(_('Is Active'), default=True)
    order = models.IntegerField(_('Ordering'), blank=True, null=True, default=0)

    def __unicode__(self):
        return "%s" % self.title

    class Meta:
        ordering = ('order', )


class Sitting(TimeStampedModel):
    '''
    Model to store quiz sitting of the MasterUser.
    '''
    masteruser = models.ForeignKey("users.MasterUser", blank=True, null=True)
    quiz = models.ForeignKey("quiz.Quiz", verbose_name=_('Quiz'),
                    blank=True, null=True)
    answers = JSONField(_('Answers'), blank=True, null=True)
    trialgamesave = models.ForeignKey("gamesaves.TrialGameSave", verbose_name=_('Trial Game Save Session'),
                    blank=True, null=True)
    is_completed = models.BooleanField(_('Is Completed'), default=False)


    def show_answers (self):
        data = []
        for q_data in self.answers:
            question_order = q_data["order"] + 1
            question_id = q_data["question"]
            answer = q_data["answer"]
            is_correct = q_data["is_correct"]
            question_obj = Question.objects.get(id=question_id)
            if question_obj.q_type == Question.ANSWER:
                obj = {"order": question_order, "question": question_obj, "answer": answer, "is_correct": is_correct}
            elif question_obj.q_type in [Question.SINGLE, Question.MULTI]:
                obj = {"order": question_order, "question": question_obj, "answer": [AnswerChoice.objects.get(id=a) for a in answer], "choices": question_obj.answerchoice_set.all(), "is_correct": is_correct}
            if question_obj.q_type == Question.DRAW:
                sittingimage = SittingImage.objects.get(id=answer)
                obj = {"order": question_order, "question": question_obj, "answer": sittingimage.image, "is_correct": is_correct}
            data.append(obj)
        return data

    def find_answer(self, question):
        data = ""
        for q_data in self.show_answers():
            question_obj = q_data["question"]
            if question == question_obj:
                data = q_data
        return data


class SittingImage(TimeStampedModel):
    '''
    Model to store uploaded images per sitting, linked to a Question.
    '''
    sitting = models.ForeignKey("quiz.Sitting", blank=True, null=True)
    question = models.ForeignKey("quiz.Question", verbose_name=_('Question'),
                    blank=True, null=True)
    image = models.ImageField(upload_to = 'answer_images', null=True, blank=True)

cc_savefile/users/templates/users/includes/cancel_invitation.html
{% extends "modal_template.html" %}
{% load i18n form_utils %}

{% block modal_title %}<h2>{% trans 'Cancel Invitation' %}</h2>{% endblock %}

{% block modal_body_content %}
<form action="{% url 'cancel_invitation' %}?code={{ code }}" method="post">
    {% csrf_token %}
    <p>{{ message }}</p>
</form>
{% endblock %}

{% block modal_buttons %}
{% if not cancel_success %}
<input id="modalformsubmit" type="button" class="btn btn-red pull-right" value="CANCEL INVITATION" />
{% endif %}
{% endblock %}

cc_savefile/users/templates/users/includes/invite_license.html
{% extends "modal_template.html" %}
{% load i18n form_utils %}

{% block modal_title %}<h2>{% trans 'Invite a User' %}</h2>{% endblock %}

{% block modal_body_content %}
<form action="{% url 'invite_license' license.user_id %}" class="invite-license-modal-form" method="post">
    {% csrf_token %}
    <h3>{{ license.is_trial|yesno:"Demo,Full" }} License</h3>
    {% if masteruser.trial_end_date %}
        <h4>Expires on: {{ masteruser.trial_end_date|date:"d/m/Y" }}</h4>
    {% endif %}

    {{ form|render }}
</form>
{% endblock %}

{% block modal_buttons %}
<input id="modalformsubmit" class="btn btn-success pull-right" value="Submit" />
{% endblock %}

{% block modal_close_buttons %}{% endblock %}

cc_savefile/users/templates/users/includes/invite_license_success.html
{% extends "modal_template.html" %}
{% load i18n form_utils %}

{% block modal_title %}<h2>{% trans 'Invitation is successful' %}</h2>{% endblock %}

{% block modal_body_content %}
<h3>Invited {{ full_name }} successfully</h3>
{% endblock %}

{% block modal_buttons %}
{% endblock %}

cc_savefile/users/templates/users/includes/report_contents.html
{% load i18n form_utils %}

<p>
{% if masteruser.last_activity %}
    Last Activity: {{ masteruser.get_last_activity }} ago
{% else %}
    {% if masteruser.auth_user.is_active %}
        License is activated but has not logged in before.
    {% else %}
        License is not activated yet.
    {% endif %}
{% endif %}
</p>

<div>
    {% if not masteruser.last_activity and not masteruser.auth_user.is_active %}
        <div class="license_update_form_container" data-href="{% if masteruser.is_trial %}{% url 'trialaccount_update_username_email' masteruser.id %}{% else %}{% url 'fullaccount_update_username_email' masteruser.id %}{% endif %}">
        </div>
    {% else %}
        <p>Username: {{ masteruser.username }}</p>
        <p>Email: {{ masteruser.email }}</p>
    {% endif %}
</div>

{% if masteruser.last_activity %}
    <div class="panel panel-default">
    {% for report_obj in masteruser.show_report %}
        <div class="panel-body">
            <h4>{{ report_obj.quiz }}</h4>
            {% for q_data in report_obj.report %}
                <p><strong>
                    {{ forloop.counter }}. {{ q_data.question }}
                </strong></p>
                {% if q_data.question.q_type == 1 %}
                    {% for a_data in q_data.answers %}
                        <p>
                            {{ a_data.answer }} ({{ a_data.count }}/{{ report_obj.sittings }})
                        </p>
                    {% endfor %}
                {% elif q_data.question.q_type == 2 or q_data.question.q_type == 3 %}
                    <ul>
                    {% for a_data in q_data.answers %}
                        <li>
                            {{ a_data.answer.content }} ({{ a_data.count }}/{{ report_obj.sittings }})
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <div style="position:relative;">
                    {% for a_data in q_data.answers %}
                        <img src="{{ a_data.answer.url }}" style="position:{% if forloop.first %}relative{% else %}absolute{% endif %}; z-index: {{ forloop.counter }}; top: 0; left: 0; opacity: 0.2; filter: alpha(opacity=20);">
                    {% endfor %}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endfor %}
    </div>
{% endif %}

{% comment %}
{% for sitting in masteruser.sitting_set.all %}
<div class="panel panel-default">
    <div class="panel-body">
    {% for data in sitting.show_answers %}
        <p>{{ data.order }}. {{ data.question }}</p>
        {% if data.question.q_type == 1 %}
            {% if data.is_correct %}
                <p style="color:green">{{ data.answer }}</p>
            {% else %}
                <p style="color:red">{{ data.answer }} <i class="fa fa-times"></i></p>
                <p>{{ data.question.answer_text }} <i class="fa fa-check"></i></p>
            {% endif %}
        {% elif data.question.q_type == 2 or data.question.q_type == 3 %}
            <ul>
            {% for a in data.question.answerchoice_set.all %}
                <li style="{% if a.is_correct_answer %}color:green;{% elif a.id in data.answer and not a.is_correct_answer %}color:red;{% endif %}">
                    {{ a.content }}
                    {% if a.id in data.answer %} <span class="label label-warning">Chosen</span>{% endif %}
                    {% if a.is_correct_answer %} <i class="fa fa-check"></i>
                    {% elif a.id in data.answer and not a.is_correct_answer %} <i class="fa fa-times"></i>{% endif %}
                </li>
            {% endfor %}
            </ul>
        {% elif data.question.q_type == 4 %}
            <p>{% if data.answer %}<img src="{{ data.answer.url }}">{% endif %}</p>
        {% endif %}
    {% endfor %}
    </div>
</div>
{% endfor %}
{% endcomment %}

cc_savefile/users/templates/users/includes/request_more_demo_form.html
{% load i18n form_utils %}

<form action="{% url 'request_more_demo' %}" method="post" id="{{ form_id }}" data-redirect="{% url 'schooluser_management' %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    <h5>Number of Trial Licenses</h5>
    {% with form.demo_accounts_num as field %}
        {% include "form_utils/fields_as_lis-nolabel.html" %}
    {% endwith %}
    <h5>Trial Start Date</h5>
    {% with form.demo_start_date as field %}
        {% include "form_utils/fields_as_lis-nolabel.html" %}
    {% endwith %}
    <div class="row" style="margin-top:10px;">
        <div class="col-xs-3 form-submit-btn-container"><button type="button" class="btn btn-lightgrey btn-cancel-invite">CANCEL</button></div>
        <div class="col-xs-9 form-submit-btn-container"><input class="btn btn-green btn-send-invite" type="submit" id="ajaxformsubmit" value="SUBMIT" /></div>
    </div>

</form>

cc_savefile/users/templates/users/includes/request_more_freefull_form.html
{% load i18n form_utils %}

<form action="{% url 'request_more_free_full' %}" method="post" id="{{ form_id }}" data-redirect="{% url 'schooluser_management' %}">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    <h5>Number of Trial Licenses</h5>
    {% with form.freefull_accounts_num as field %}
        {% include "form_utils/fields_as_lis-nolabel.html" %}
    {% endwith %}
    <h5>Trial Start Date</h5>
    {% with form.freefull_start_date as field %}
        {% include "form_utils/fields_as_lis-nolabel.html" %}
    {% endwith %}
    <div class="row" style="margin-top:10px;">
        <div class="col-xs-3 form-submit-btn-container"><button type="button" class="btn btn-lightgrey btn-cancel-invite">CANCEL</button></div>
        <div class="col-xs-9 form-submit-btn-container"><input class="btn btn-green btn-send-invite" type="submit" id="ajaxformsubmit" value="SUBMIT" /></div>
    </div>

</form>

cc_savefile/users/templates/users/includes/signup_login_modal.html
{% extends "modal_template.html" %}
{% load i18n form_utils %}

{% block modal_title %}{% trans 'Sign Up' %}{% endblock %}

{% block modal_body_content %}
<div id="index-signup-login-tab">
    <ul class="nav nav-pills nav-pills-yellow" id="signup-login-buttons-container">
        <li class="pull-left active" id="btn-signup-container">
            <a data-toggle="tab" href="#tab_signup" class="btn btn-yellow" id="btn-signup">
                SIGN UP
            </a>
        </li>
        <li class="pull-left" id="btn-login-container">
            <a data-toggle="tab" href="#tab_login" class="btn btn-yellow" id="btn-login">
                LOG IN
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="tab_signup" class="tab-pane fade in form-container active">
            {% with signup_form as form %}
                {% include "users/register_form.html" %}
            {% endwith %}
        </div>

        <div id="tab_login" class="tab-pane fade in form-container">
            {% url 'store' as store_url %}
            {% with form=login_form redirect_url=store_url %}
                {% include "registration/login.html" %}
            {% endwith %}
        </div>
    </div>
</div>
{% endblock %}

{% block modal_buttons %}
{# <input id="modalformsubmit" type="button" class="btn btn-red pull-right" value="CANCEL INVITATION" /> #}
{% endblock %}

cc_savefile/users/templates/users/includes/upload_csv.html
{% load i18n form_utils %}

<form action="{% url 'import_account_from_csv' %}" method="post" enctype="multipart/form-data" id="{{ form_id }}">
    {% csrf_token %}
    <div class="row">
        You can invite multiple users to use unassigned licenses by importing them from a CSV file.
    </div>
    <div class="row">
        <strong>Step 1: Download CSV template</strong><br>
        <a class="btn btn-default" href="{% url 'export_licenses_as_csv' %}">Download CSV Template</a>
    </div>

    <div class="row">
        <strong>Step 2: Upload the CSV file</strong><br>

        {{ form.schooluser }}

        <div class="col-md-9 form-input-container">
            <label for="file-upload" class="btn btn-default">
            Browse
                {{ form.csv_file }}
            </label>

        </div>
    </div>
    <div class="row"></div>
    <div class="row">
        <div class="col-xs-6 form-submit-btn-container">
            <input class="btn btn-blue btn-send-invite" type="submit" value="IMPORT & SEND INVITATION" />
        </div>
    </div>

    {% if form.csv_file.errors %}
        {% for error in form.csv_file.errors %}
        <div class="row field-errors-container">
            <div class="col-md-12 help-block error-block">
                <span class="fa fa-exclamation-triangle"></span> {{ error }}
            </div>
        </div>
        {% endfor %}
    {% endif %}

</form>